run:
  deadline: 120s
  tests: false

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    #- dupl  # we do have some duplicated lines of test logic, that's life
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    #- nolintlint
    # nolintlint is currently disabled because some linters don't yet work with Go 1.18, but we may have nolint
    # directives that would be needed to suppress those linters if they did work.
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  fast: false

linters-settings:
  gofmt:
    simplify: false
  goimports:
    local-prefixes: gopkg.in/launchdarkly,github.com/launchdarkly
  
issues:
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
