version: 2.1

workflows:
  version: 2
  test:
    jobs:
    - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: make test
      - run: make lint
