name: Publish Artifacts
description: 'Publish artifacts to Github Release'
inputs:
  token:
    description: 'Token to use for publishing.'
    required: true
  tag:
    description: 'Tag to upload artifacts to.'
    required: true

runs:
  using: composite
  steps:
    - name: Run Goreleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        version: latest
        args: release --clean --skip=publish
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Upload Release Artifacts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh release upload ${{ inputs.tag }} ./dist/*.tar.gz ./dist/*.zip --clobber
