name: Publish Artifacts
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to upload artifacts to.'
        required: true
        type: string

jobs:
  release-sdk-test-harness:
    uses: ./.github/workflows/release.yml
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ inputs.tag }}
