name: Publish Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of an existing draft release to upload release artifacts to.'
        required: true
        type: string
      publish_release:
        description: 'Publish (un-draft) the release after all artifacts are uploaded?'
        type: boolean
        required: false
        default: true

jobs:
  release-sdk-test-harness:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Needed for goreleaser to inspect tags.
      - uses: ./.github/actions/ci
        with:
          run_linter: 'false'
      - uses: ./.github/actions/publish
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag }}

  publish-release:
    needs: release-sdk-test-harness
    if: ${{ inputs.publish_release }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.tag }}
        run: >
          gh release edit "$TAG_NAME"
          --repo ${{ github.repository }}
          --draft=false
