on:
  workflow_call:
    inputs:
      tag:
        required: true
        description: 'The tag to upload release artifacts to.'
        type: string
    secrets:
      token:
        required: true
        description: 'GitHub token'

jobs:
  release-sdk-test-harness:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        run_linter: 'false'
    - uses: ./.github/actions/publish
      with:
        token: ${{ secrets.token }}
        tag: ${{ github.event.inputs.tag }}
