on:
  workflow_call:
    inputs:
      token:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  release-sdk-test-harness:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/ci
      with:
        run_linter: 'false'
    - uses: ./.github/actions/publish
      with:
        token: ${{ github.event.inputs.token }}
        tag: ${{ github.event.inputs.tag }}
